devops: Patching the rollout status in k8s deploymenty

diff --git a/.github/actions/k8s-deploy/action.yml b/.github/actions/k8s-deploy/action.yml
--- a/.github/actions/k8s-deploy/action.yml
+++ b/.github/actions/k8s-deploy/action.yml
@@ -139,9 +139,20 @@ runs:
         if kubectl -n ${{ inputs.K8S_NAMESPACE }} get deploy ${{ inputs.SVC_NAME }} >/dev/null 2>&1 ; then
           for i in {1..2} ; do
             echo "${i} : Checking the status for the K8s Deployment"
-            kubectl --namespace ${{ inputs.K8S_NAMESPACE }} rollout status deploy ${{ inputs.SVC_NAME }} -w --timeout=${{ inputs.HELM_TIMEOUT }} && break
-            sleep 30
+            kubectl --namespace ${{ inputs.K8S_NAMESPACE }} rollout status deploy ${{ inputs.SVC_NAME }} -w --timeout=${{ inputs.HELM_TIMEOUT }}
+            if [[ $? -eq 0 ]] ; then
+              ROLLOUT_STATUS="success"
+              break
+            else
+              ROLLOUT_STATUS="failed"
+              sleep 30
+            fi
           done
+        fi
+
+        if [[ ${ROLLOUT_STATUS} == "failed" ]] ; then
+          echo "Deployment failed for the service ${{ inputs.SVC_NAME }}...!"
+          exit 1
         fi
 
         helm repo remove ${{ inputs.SVC_NAME }}
